    # Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

global:
  rabbitmq:
    host:
      value: ""
    username:
      value: guest
    password:
      value: guest
  keycloak:
    url: ""
    name: keycloak
    service:
      type: http
      port: 80
    realm: ""
    reource: ""
  gateway:
    host: ""  

db:
  uri:
  username:
  password:
  driver:
  platform:
  generateDdl: "false"
  ddlAuto: "none"
init:
  container:
    image: alpine:3.8
    imagePullPolicy: IfNotPresent
postgres:
  enabled: false
  name: postgres
  port: 5432
  username: postgres
  password:
  generateDdl: "false"
  ddlAuto: "none"

javaOpts:
  xmx: 2048m
  xms: 512m
  other: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90


## Allows the specification of additional environment variables
extraEnv: |
  # - name: ACT_KEYCLOAK_URL
  #   valueFrom:
  #     configMapKeyRef:
  #       name: {{ .Release.Name }}-keycloak-http
  #       key: expose-keycloak-service-key

# only set this variable if a private registry secret is needed to pull the image
#registryPullSecrets: private-registry-secret
image:
  repository: activiti/activiti-cloud-query
  tag: 7.0.0.SR1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "false"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 1.5
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 4
  successThreshold: 1
  failureThreshold: 4
readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 4
terminationGracePeriodSeconds: 20

ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hostName: 

  ## Set to true to enable websockets
  ws:
    enabled: false

  path: /query

  ## Set this to true in order to enable TLS on the ingress record
  tls: 

  ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
  tlsSecret: 

  ## Ingress annotations done as key:value pairs
  annotations: 
    ingress:
  # Set to true to enable ingress record generation
  
  #path: /notifications # configure base path template for ingress, i.e. /{{ .Release.Name }}/notifications
  
  actuator: 
    enabled: true
    path: /notifications/actuator
  graphiql: 
    enabled: true
    path: /notifications/graphiql
  web:
    enabled: true
    path: /notifications/graphql
  ws: 
    enabled: true
    path: /notifications/ws/graphql
  query: 
    enabled: true
    path: /query/?(.*)
  audit: 
    enabled: true
    path: /audit/?(.*)




  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-header: X-Forwarded-For, X-Forwarded-Proto,
      X-Forwarded-Port, X-Forwarded-Prefix, Authorization, Content-Type, Accept
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"

  notificationsannotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET,PUT,POST,DELETE,PATCH,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"   
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers 'Access-Control-Allow-Origin: $http_origin';
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: "activiti-cloud-notifications-graphql-route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "md5"
    nginx.ingress.kubernetes.io/session-cookie-path: '{{ include "common.ingress-path" . }}'
